name: Crawling

on:
  push:
    branches: master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 12 * * *'


jobs:
  build:
    #runs-on: ubuntu-22.04
    runs-on: ubuntu-latest

    strategy:
      matrix:
        #python-version: [ 3.11.4 ]
        python-version: [ 3.12.3 ] #upgrade python while ubuntu-latest = 24.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - run: bash ./bin/github_data.sh
